name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install

        #  run server in dev mode
      - name: Start server
        run: pnpm run dev

      - name: Run unit tests
        run: pnpm run test

      - name: Run E2E tests
        run: pnpm run e2e
